
  import * as awssdkclients3 from '@aws-sdk/client-s3'
import * as inquirerconfirm from '@inquirer/confirm'
import * as typesnode from '@types/node'
import * as typesreact from '@types/react'
import * as chalk from 'chalk'
import * as dayjs from 'dayjs'
import * as debug from 'debug'
import * as execa from 'execa'
import * as htmlentities from 'html-entities'
import * as reactdom from 'react-dom'
import * as reactreconciler from 'react-reconciler'
import * as react from 'react'
import * as zod from 'zod'
  