ARG BUILD_ARCH=arm64
FROM <%= DOCKER_IMAGE_YARN_BASE_TAG %>-linux-$BUILD_ARCH

COPY docker/images/41-slide/fs-root /

RUN echo 'Install dependencies' \
   && cd /workspace/.dinghy/slide \
    && yarn install --immutable