= ReactIAC

image:https://github.com/reactiac/reactiac/actions/workflows/release.yml/badge.svg[release,link=https://github.com/reactiac/reactiac/actions/workflows/release.yml] image:https://github.com/reactiac/reactiac/actions/workflows/verification.yml/badge.svg[verification,link=https://github.com/reactiac/reactiac/actions/workflows/verification.yml]

== Commands



    git init --initial-branch=main

    pnpm install -g oclif
    oclif generate mynewcli

    pnpm -r build
    pnpm --filter reactiac-cli dev hello world
    pnpm --filter reactiac-cli cli hello world
    pnpm --filter cli dev tf init



== Release management Commands

    pnpm aws-login
    pnpm -r publish --no-git-checks --force


    aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 313225491971.dkr.ecr.eu-west-1.amazonaws.com
    docker buildx build --secret "id=npm,src=${HOME}/.npmrc" -f docker/release/Dockerfile -t 313225491971.dkr.ecr.eu-west-1.amazonaws.com/test/cli:test .
    docker push 313225491971.dkr.ecr.eu-west-1.amazonaws.com/test/cli:test

    # sample test command
    docker run -v $(pwd)=${pwd} -w $(pwd) 313225491971.dkr.ecr.eu-west-1.amazonaws.com/test/cli:0.0.1-20250323-075340-67f3a28 diagram gen --app-home clients/cli/test/fixtures/standard-diagrams
