= ReactIAC

image:https://github.com/reactiac/reactiac/actions/workflows/release.yml/badge.svg[release,link=https://github.com/reactiac/reactiac/actions/workflows/release.yml] image:https://github.com/reactiac/reactiac/actions/workflows/verification.yml/badge.svg[verification,link=https://github.com/reactiac/reactiac/actions/workflows/verification.yml]

== Commands



    git init --initial-branch=main

    pnpm install -g oclif
    oclif generate mynewcli

    pnpm -r build
    pnpm --filter reactiac-cli dev hello world
    pnpm --filter reactiac-cli cli hello world
    pnpm --filter cli dev tf init



== Local Commands

    docker pull public.ecr.aws/f2v6q7q7/reactiac/reactiac:latest-linux-arm64

    docker run -it -v $(pwd)/examples/web/1-shape:/workspace/app public.ecr.aws/f2v6q7q7/reactiac/reactiac:latest-linux-arm64 tf gen

    docker run -it -v $(pwd)/examples/web/5-data:/workspace/app public.ecr.aws/f2v6q7q7/reactiac/reactiac:latest-linux-arm64 tf gen
    
    docker pull public.ecr.aws/f2v6q7q7/reactiac/reactiac:latest-linux-arm64
    docker run -it -v $(pwd)/examples/iac/cf-site:/workspace/app public.ecr.aws/f2v6q7q7/reactiac/reactiac:latest-linux-arm64 tf gip

    rm -rf sample-app && reactiac create sample-app && cd sample-app && reactiac devcontainer && cd ..
    