= ReactIAC

image:https://github.com/reactiac/reactiac/actions/workflows/release.yml/badge.svg[release,link=https://github.com/reactiac/reactiac/actions/workflows/release.yml] image:https://github.com/reactiac/reactiac/actions/workflows/verification.yml/badge.svg[verification,link=https://github.com/reactiac/reactiac/actions/workflows/verification.yml]

== Commands



    git init --initial-branch=main

    pnpm install -g oclif
    oclif generate mynewcli

    pnpm -r build
    pnpm --filter reactiac-cli dev hello world
    pnpm --filter reactiac-cli cli hello world
    pnpm --filter cli dev tf init



== Local Commands


    (cd scripts/tasks ; deno task clean)
    (cd scripts/tasks ; deno task version-release)

    (cd scripts/tasks ; deno task npm-build)
    (cd scripts/tasks ; deno task aws-npm-login)
    (cd scripts/tasks ; deno task npm-publish)

    (cd scripts/tasks ; deno task cli-build-aarch64-apple-darwin && cp ../../build/cli/aarch64-apple-darwin/reactiac ~/.reactiac/bin/ && reactiac -h)

    (cd scripts/tasks ; deno task cli-publish)
    curl -fsSL https://play.reactiac.dev/download/install.sh | sh


    (cd scripts/tasks ; deno task aws-ecr-login)
    (cd scripts/tasks ; deno task docker-build-arm64)
    (cd scripts/tasks ; deno task docker-build)


    (rm -rf ~/Downloads/test1 && reactiac init ~/Downloads/test1 && cd ~/Downloads/test1 && reactiac dc)
    (cd standalone/cli ; deno task run devcontainer --debug --xworkspace /reactiac --xmounts ../../:/reactiac  --app-home ../../examples/web/1-shape)

    (cd workspace ; deno task json)