export {
  AwsObservabilityadminCentralizationRuleForOrganization,
  useAwsObservabilityadminCentralizationRuleForOrganization,
  useAwsObservabilityadminCentralizationRuleForOrganizations,
} from './AwsObservabilityadminCentralizationRuleForOrganization.tsx'
