/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    "get-started": [
        {
            type: "category",
            label: "Get Started",
            collapsible: false,
            link: {
                type: "doc",
                id: "get-started",
            },
            items: [{
                type: "autogenerated",
                dirName: "get-started",
            }],
        },
    ],
    references: [
        {
            type: "category",
            label: "References",
            collapsible: false,
            link: {
                type: "doc",
                id: "references",
            },
            items: [
                {
                    type: "category",
                    label: "Commands",
                    link: {
                        type: "doc",
                        id: "references/commands",
                    },
                    items: [{
                        type: "autogenerated",
                        dirName: "references/commands",
                    }],
                },
                {
                    type: "category",
                    label: "Attributes",
                    link: {
                        type: "doc",
                        id: "references/attributes",
                    },
                    items: [{
                        type: "autogenerated",
                        dirName: "references/attributes",
                    }],
                },
                {
                    type: "category",
                    label: "Diagrams",
                    collapsible: false,
                    link: {
                        type: "doc",
                        id: "references/diagrams",
                    },
                    items: [
                        {
                            type: "category",
                            label: "Composites",
                            link: {
                                type: "doc",
                                id: "references/diagrams/composites",
                            },
                            items: [{
                                type: "autogenerated",
                                dirName: "references/diagrams/composites",
                            }],
                        },
                        {
                            type: "link",
                            label: "/references/diagrams/Elements/",
                            href: "/rewrite-url",
                        },
                    ],
                },
                {
                    type: "category",
                    label: "TF AWS",
                    collapsible: false,
                    link: {
                        type: "doc",
                        id: "references/tf-aws",
                    },
                    items: [
                        {
                            type: "category",
                            label: "Foundation",
                            link: {
                                type: "doc",
                                id: "references/tf-aws/foundation",
                            },
                            items: [{
                                type: "autogenerated",
                                dirName: "references/tf-aws/foundation",
                            }],
                        },
                        {
                            type: "link",
                            label: "/references/tf-aws/Services/",
                            href: "/rewrite-url",
                        },
                    ],
                },
            ],
        },
    ],
    "examples": [
        {
            type: "category",
            label: "Examples",
            collapsible: false,
            link: {
                type: "doc",
                id: "examples",
            },
            items: [{
                type: "autogenerated",
                dirName: "examples",
            }],
        },
    ],
    community: [
        {
            type: "category",
            label: "Community",
            collapsible: false,
            link: {
                type: "doc",
                id: "community",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "community",
                },
                {
                    type: "link",
                    label: "GitHub Repository",
                    href: "https://github.com/dinghydev/dinghy",
                },
                {
                    type: "link",
                    label: "GitHub Discussions",
                    href: "https://github.com/dinghydev/dinghy/discussions",
                },
                {
                    type: "link",
                    label: "GitHub Issues",
                    href: "https://github.com/dinghydev/dinghy/issues",
                },
                {
                    type: "link",
                    label: "GitHub Security",
                    href: "https://github.com/dinghydev/dinghy/security",
                },
            ],
        },
    ],
};
