/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    "get-started": [
        {
            type: "category",
            label: "Get Started",
            collapsible: false,
            link: {
                type: "doc",
                id: "get-started",
            },
            items: [{
                type: "autogenerated",
                dirName: "get-started",
            }],
        },
    ],
    references: [
        {
            type: "category",
            label: "References",
            collapsible: false,
            link: {
                type: "doc",
                id: "references",
            },
            items: [
                {
                    type: "category",
                    label: "Diagrams",
                    collapsible: false,
                    link: {
                        type: "doc",
                        id: "references/diagrams",
                    },
                    items: [
                        {
                            type: "link",
                            label: "Elements",
                            href: "/references/diagrams/elements/rewrite-url",
                        },
                    ],
                },
            ],
        },
    ],
    contribute: [
        {
            type: "category",
            label: "Contribute",
            collapsible: false,
            link: {
                type: "doc",
                id: "contribute",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "contribute",
                },
                {
                    type: "link",
                    label: "GitHub Repository",
                    href: "https://github.com/dinghydev/dinghy",
                },
                {
                    type: "link",
                    label: "GitHub Discussions",
                    href: "https://github.com/dinghydev/dinghy/discussions",
                },
                {
                    type: "link",
                    label: "GitHub Issues",
                    href: "https://github.com/dinghydev/dinghy/issues",
                },
                {
                    type: "link",
                    label: "GitHub Security",
                    href: "https://github.com/dinghydev/dinghy/security",
                },
            ],
        },
    ],
};
