/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  'references': [
    {
      type: 'category',
      label: '/References',
      collapsible: false,
      link: {
        type: 'doc',
        id: 'rewrite-url',
      },
      items: [
        {
          type: 'doc',
          label: '/References/Commands',
          id: 'rewrite-url',
        },
        {
          type: 'doc',
          label: '/References/Attributes',
          id: 'rewrite-url',
        },
        {
          type: 'category',
          label: 'Diagrams',
          collapsible: false,
          link: {
            type: 'doc',
            id: 'README',
          },
          items: [
            {
              type: 'category',
              label: 'Composites',
              link: {
                type: 'doc',
                id: 'composites',
              },
              items: [{
                type: 'autogenerated',
                dirName: 'composites',
              }],
            },
            {
              type: 'category',
              label: 'Elements',
              link: {
                type: 'doc',
                id: 'elements',
              },
              items: [{
                type: 'autogenerated',
                dirName: 'elements',
              }],
            },
          ],
        },
        {
          type: 'doc',
          label: '/References/TF AWS/',
          id: 'rewrite-url',
        },
      ],
    },
  ],
}
