ARG BUILD_ARCH=arm64
FROM <%= DOCKER_IMAGE_ENGINE_BASE_TAG %>-linux-$BUILD_ARCH

COPY . /workspace/.dinghy

RUN cd /workspace/.dinghy && \
    . /root/.bashrc && \
    deno run -A cache-installer.ts && \
    rm -rf deno.* cache-installer.ts engine/packages-to-cache.ts engine/deno.jsonc
