import { extendStyle, Shape } from '@diac/base-components'
import type { DiagramNodeProps } from '@diac/base-components'

export const APP_NON_SAP = {
  _style: {
    entity:
      'shape=image;editableCssRules=.*;verticalLabelPosition=bottom;labelBackgroundColor=default;verticalAlign=top;aspect=fixed;imageAspect=0;image=data:image/svg+xml,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0wLjUgLTAuNSAyOCAyNC41NTMiIGhlaWdodD0iMjQuNTUzIiB3aWR0aD0iMjgiPiYjeGE7CSAgPHN0eWxlIHR5cGU9InRleHQvY3NzIj4uc3QwIHsgc3RvcC1jb2xvcjogcmdiKDkxLCAxMTUsIDEzOSk7IH0gLnN0MSB7IHN0b3AtY29sb3I6IHJnYigzNCwgNTMsIDcyKTsgfSA8L3N0eWxlPiYjeGE7CTxkZWZzPiYjeGE7CQk8bGluZWFyR3JhZGllbnQgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiIHkyPSIyNC41NzgiIHgyPSIyMC42MSIgeTE9IjIuOTg1IiB4MT0iMi4wMzkiIGlkPSJBIj4mI3hhOwkJCTxzdG9wIGNsYXNzPSJzdDAiLz4mI3hhOwkJCTxzdG9wIGNsYXNzPSJzdDEiIG9mZnNldD0iMSIvPiYjeGE7CQk8L2xpbmVhckdyYWRpZW50PiYjeGE7CTwvZGVmcz4mI3hhOwk8cGF0aCBmaWxsPSJ1cmwoI0EpIiBkPSJNMjMuMjg5LS41YzEuMjAyIDAgMi4yMDUuNDAyIDMuMDA4IDEuMjA0UzI3LjUgMi41MDYgMjcuNSAzLjcxdjE2LjEzM2E0LjIgNC4yIDAgMCAxLTEuMjA0IDMuMDA4Yy0uODAyLjgwMS0xLjgwMiAxLjIwMi0zLjAwNiAxLjIwMkgzLjcxMWMtMS4yMDIgMC0yLjIwNS0uNDAxLTMuMDA4LTEuMjAyYTQuMiA0LjIgMCAwIDEtMS4yMDItMy4wMDhWMy43MWMwLTEuMjAyLjQwMi0yLjIwNSAxLjIwNC0zLjAwOFMyLjUwNy0uNSAzLjcwOS0uNXpNMi4yOSA1LjA3OWgyMi40MlYzLjcxYzAtLjk0Ny0uNDczLTEuNDIxLTEuNDIxLTEuNDIxSDMuNzExYy0uMzgyLS4wMDctLjc1My4xMy0xLjAzOS4zODMtLjI1NC4yNTQtLjM4MS42LS4zODEgMS4wMzh2MS4zNjd6bTIyLjQyIDIuODQ0SDIuMjl2MTEuOTIxYzAgLjQwMi4xMjguNzMuMzgxLjk4NS4yODcuMjUzLjY1Ny4zODkgMS4wMzkuMzgxaDE5LjU3OGMuOTQ3IDAgMS40MjEtLjQ1NSAxLjQyMS0xLjM2N1Y3LjkyMXoiLz4mI3hhOzwvc3ZnPg==;strokeColor=none;',
  },
  _width: 28,
  _height: 25,
}

export function AppNonSap(props: DiagramNodeProps) {
  return (
    <Shape
      {...APP_NON_SAP}
      {...props}
      _style={extendStyle(APP_NON_SAP, props)}
    />
  )
}
