/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    "references": [
        {
            type: "category",
            label: "References",
            collapsible: false,
            link: {
                type: "doc",
                id: "rewrite-url",
            },
            items: [
                {
                    type: "category",
                    label: "Diagrams",
                    collapsible: false,
                    link: {
                        type: "doc",
                        id: "rewrite-url",
                    },
                    items: [
                        {
                            type: "category",
                            label: "Elements",
                            collapsible: false,
                            link: {
                                type: "doc",
                                id: "README",
                            },
                            items: [{
                                type: "category",
                                label: "Entities",
                                link: {
                                    type: "doc",
                                    id: "entities",
                                },
                                items: [{
                                    type: "autogenerated",
                                    dirName: "entities",
                                }],
                            }, {
                                type: "category",
                                label: "Containers",
                                link: {
                                    type: "doc",
                                    id: "containers",
                                },
                                items: [{
                                    type: "autogenerated",
                                    dirName: "containers",
                                }],
                            }, {
                                type: "category",
                                label: "Dependencies",
                                link: {
                                    type: "doc",
                                    id: "dependencies",
                                },
                                items: [{
                                    type: "autogenerated",
                                    dirName: "dependencies",
                                }],
                            }],
                        },
                    ],
                },
            ],
        },
    ],
};
