title: Sample Docusaurus Site
tagline: Sample Dinosaurs are cool
themeConfig:
  image: img/docusaurus-social-card.jpg
  navbar:
    title: My Site
    logo:
      alt: My Site Logo
      src: img/logo.svg
    items:
      - type: docSidebar
        sidebarId: tutorialSidebar
        position: left
        label: Tutorial
      - to: /blog
        label: Blog
        position: left
      - href: https://github.com/facebook/docusaurus
        label: GitHub
        position: right
  footer:
    style: dark
    links:
      - title: Docs
        items:
          - label: Tutorial
            to: /docs/intro
      - title: Community
        items:
          - label: Stack Overflow
            href: https://stackoverflow.com/questions/tagged/docusaurus
          - label: Discord
            href: https://discordapp.com/invite/docusaurus
          - label: X
            href: https://x.com/docusaurus
      - title: More
        items:
          - label: Blog
            to: /blog
          - label: GitHub
            href: https://github.com/facebook/docusaurus
    copyright: "Copyright © 2025 My Project, Inc. Built with Docusaurus."
