import {
  extendStyle,
  getRenderOptions,
  NodeProps,
  resolvableValue,
  Shape,
  useTypedNode,
} from '@dinghy/base-components'

import z from 'zod'
import { AWS_CLOUD } from '@dinghy/diagrams/containersAwsGroups'

export const InputSchema = z.object({
  providerId: z.string(),
  alias: z.string().optional(),
  access_key: resolvableValue(z.string().optional()),
  allowed_account_ids: resolvableValue(z.string().array().optional()),
  custom_ca_bundle: resolvableValue(z.string().optional()),
  ec2_metadata_service_endpoint: resolvableValue(z.string().optional()),
  ec2_metadata_service_endpoint_mode: resolvableValue(z.string().optional()),
  forbidden_account_ids: resolvableValue(z.string().array().optional()),
  http_proxy: resolvableValue(z.string().optional()),
  https_proxy: resolvableValue(z.string().optional()),
  insecure: resolvableValue(z.boolean().optional()),
  max_retries: resolvableValue(z.number().optional()),
  no_proxy: resolvableValue(z.string().optional()),
  profile: resolvableValue(z.string().optional()),
  region: resolvableValue(z.string().optional()),
  retry_mode: resolvableValue(z.string().optional()),
  s3_us_east_1_regional_endpoint: resolvableValue(z.string().optional()),
  s3_use_path_style: resolvableValue(z.boolean().optional()),
  secret_key: resolvableValue(z.string().optional()),
  shared_config_files: resolvableValue(z.string().array().optional()),
  shared_credentials_files: resolvableValue(z.string().array().optional()),
  skip_credentials_validation: resolvableValue(z.boolean().optional()),
  skip_metadata_api_check: resolvableValue(z.string().optional()),
  skip_region_validation: resolvableValue(z.boolean().optional()),
  skip_requesting_account_id: resolvableValue(z.boolean().optional()),
  sts_region: resolvableValue(z.string().optional()),
  tag_policy_compliance: resolvableValue(z.string().optional()),
  token: resolvableValue(z.string().optional()),
  token_bucket_rate_limiter_capacity: resolvableValue(z.number().optional()),
  use_dualstack_endpoint: resolvableValue(z.boolean().optional()),
  use_fips_endpoint: resolvableValue(z.boolean().optional()),
  user_agent: resolvableValue(z.string().array().optional()),
  assume_role: resolvableValue(
    z.object({
      duration: z.string().optional(),
      external_id: z.string().optional(),
      policy: z.string().optional(),
      policy_arns: z.string().array().optional(),
      role_arn: z.string().optional(),
      session_name: z.string().optional(),
      source_identity: z.string().optional(),
      tags: z.record(z.string(), z.string()).optional(),
      transitive_tag_keys: z.string().array().optional(),
    }).array().optional(),
  ),
  assume_role_with_web_identity: resolvableValue(
    z.object({
      duration: z.string().optional(),
      policy: z.string().optional(),
      policy_arns: z.string().array().optional(),
      role_arn: z.string().optional(),
      session_name: z.string().optional(),
      web_identity_token: z.string().optional(),
      web_identity_token_file: z.string().optional(),
    }).array().optional(),
  ),
  default_tags: resolvableValue(
    z.object({
      tags: z.record(z.string(), z.string()).optional(),
    }).array().optional(),
  ),
  endpoints: resolvableValue(
    z.object({
      accessanalyzer: z.string().optional(),
      account: z.string().optional(),
      acm: z.string().optional(),
      acmpca: z.string().optional(),
      amg: z.string().optional(),
      amp: z.string().optional(),
      amplify: z.string().optional(),
      apigateway: z.string().optional(),
      apigatewayv2: z.string().optional(),
      appautoscaling: z.string().optional(),
      appconfig: z.string().optional(),
      appfabric: z.string().optional(),
      appflow: z.string().optional(),
      appintegrations: z.string().optional(),
      appintegrationsservice: z.string().optional(),
      applicationautoscaling: z.string().optional(),
      applicationinsights: z.string().optional(),
      applicationsignals: z.string().optional(),
      appmesh: z.string().optional(),
      appregistry: z.string().optional(),
      apprunner: z.string().optional(),
      appstream: z.string().optional(),
      appsync: z.string().optional(),
      arcregionswitch: z.string().optional(),
      arczonalshift: z.string().optional(),
      athena: z.string().optional(),
      auditmanager: z.string().optional(),
      autoscaling: z.string().optional(),
      autoscalingplans: z.string().optional(),
      backup: z.string().optional(),
      batch: z.string().optional(),
      bcmdataexports: z.string().optional(),
      beanstalk: z.string().optional(),
      bedrock: z.string().optional(),
      bedrockagent: z.string().optional(),
      bedrockagentcore: z.string().optional(),
      billing: z.string().optional(),
      budgets: z.string().optional(),
      ce: z.string().optional(),
      chatbot: z.string().optional(),
      chime: z.string().optional(),
      chimesdkmediapipelines: z.string().optional(),
      chimesdkvoice: z.string().optional(),
      cleanrooms: z.string().optional(),
      cloud9: z.string().optional(),
      cloudcontrol: z.string().optional(),
      cloudcontrolapi: z.string().optional(),
      cloudformation: z.string().optional(),
      cloudfront: z.string().optional(),
      cloudfrontkeyvaluestore: z.string().optional(),
      cloudhsm: z.string().optional(),
      cloudhsmv2: z.string().optional(),
      cloudsearch: z.string().optional(),
      cloudtrail: z.string().optional(),
      cloudwatch: z.string().optional(),
      cloudwatchevents: z.string().optional(),
      cloudwatchevidently: z.string().optional(),
      cloudwatchlog: z.string().optional(),
      cloudwatchlogs: z.string().optional(),
      cloudwatchobservabilityaccessmanager: z.string().optional(),
      cloudwatchrum: z.string().optional(),
      codeartifact: z.string().optional(),
      codebuild: z.string().optional(),
      codecatalyst: z.string().optional(),
      codecommit: z.string().optional(),
      codeconnections: z.string().optional(),
      codedeploy: z.string().optional(),
      codeguruprofiler: z.string().optional(),
      codegurureviewer: z.string().optional(),
      codepipeline: z.string().optional(),
      codestarconnections: z.string().optional(),
      codestarnotifications: z.string().optional(),
      cognitoidentity: z.string().optional(),
      cognitoidentityprovider: z.string().optional(),
      cognitoidp: z.string().optional(),
      comprehend: z.string().optional(),
      computeoptimizer: z.string().optional(),
      config: z.string().optional(),
      configservice: z.string().optional(),
      connect: z.string().optional(),
      connectcases: z.string().optional(),
      controltower: z.string().optional(),
      costandusagereportservice: z.string().optional(),
      costexplorer: z.string().optional(),
      costoptimizationhub: z.string().optional(),
      cur: z.string().optional(),
      customerprofiles: z.string().optional(),
      databasemigration: z.string().optional(),
      databasemigrationservice: z.string().optional(),
      databrew: z.string().optional(),
      dataexchange: z.string().optional(),
      datapipeline: z.string().optional(),
      datasync: z.string().optional(),
      datazone: z.string().optional(),
      dax: z.string().optional(),
      deploy: z.string().optional(),
      detective: z.string().optional(),
      devicefarm: z.string().optional(),
      devopsguru: z.string().optional(),
      directconnect: z.string().optional(),
      directoryservice: z.string().optional(),
      dlm: z.string().optional(),
      dms: z.string().optional(),
      docdb: z.string().optional(),
      docdbelastic: z.string().optional(),
      drs: z.string().optional(),
      ds: z.string().optional(),
      dsql: z.string().optional(),
      dynamodb: z.string().optional(),
      ec2: z.string().optional(),
      ecr: z.string().optional(),
      ecrpublic: z.string().optional(),
      ecs: z.string().optional(),
      efs: z.string().optional(),
      eks: z.string().optional(),
      elasticache: z.string().optional(),
      elasticbeanstalk: z.string().optional(),
      elasticloadbalancing: z.string().optional(),
      elasticloadbalancingv2: z.string().optional(),
      elasticsearch: z.string().optional(),
      elasticsearchservice: z.string().optional(),
      elastictranscoder: z.string().optional(),
      elb: z.string().optional(),
      elbv2: z.string().optional(),
      emr: z.string().optional(),
      emrcontainers: z.string().optional(),
      emrserverless: z.string().optional(),
      es: z.string().optional(),
      eventbridge: z.string().optional(),
      events: z.string().optional(),
      evidently: z.string().optional(),
      evs: z.string().optional(),
      finspace: z.string().optional(),
      firehose: z.string().optional(),
      fis: z.string().optional(),
      fms: z.string().optional(),
      fsx: z.string().optional(),
      gamelift: z.string().optional(),
      glacier: z.string().optional(),
      globalaccelerator: z.string().optional(),
      glue: z.string().optional(),
      gluedatabrew: z.string().optional(),
      grafana: z.string().optional(),
      greengrass: z.string().optional(),
      groundstation: z.string().optional(),
      guardduty: z.string().optional(),
      healthlake: z.string().optional(),
      iam: z.string().optional(),
      identitystore: z.string().optional(),
      imagebuilder: z.string().optional(),
      inspector: z.string().optional(),
      inspector2: z.string().optional(),
      inspectorv2: z.string().optional(),
      internetmonitor: z.string().optional(),
      invoicing: z.string().optional(),
      iot: z.string().optional(),
      ivs: z.string().optional(),
      ivschat: z.string().optional(),
      kafka: z.string().optional(),
      kafkaconnect: z.string().optional(),
      kendra: z.string().optional(),
      keyspaces: z.string().optional(),
      kinesis: z.string().optional(),
      kinesisanalytics: z.string().optional(),
      kinesisanalyticsv2: z.string().optional(),
      kinesisvideo: z.string().optional(),
      kms: z.string().optional(),
      lakeformation: z.string().optional(),
      lambda: z.string().optional(),
      launchwizard: z.string().optional(),
      lex: z.string().optional(),
      lexmodelbuilding: z.string().optional(),
      lexmodelbuildingservice: z.string().optional(),
      lexmodels: z.string().optional(),
      lexmodelsv2: z.string().optional(),
      lexv2models: z.string().optional(),
      licensemanager: z.string().optional(),
      lightsail: z.string().optional(),
      location: z.string().optional(),
      locationservice: z.string().optional(),
      logs: z.string().optional(),
      m2: z.string().optional(),
      macie2: z.string().optional(),
      managedgrafana: z.string().optional(),
      mediaconnect: z.string().optional(),
      mediaconvert: z.string().optional(),
      medialive: z.string().optional(),
      mediapackage: z.string().optional(),
      mediapackagev2: z.string().optional(),
      mediapackagevod: z.string().optional(),
      mediastore: z.string().optional(),
      memorydb: z.string().optional(),
      mgn: z.string().optional(),
      mq: z.string().optional(),
      msk: z.string().optional(),
      mwaa: z.string().optional(),
      mwaaserverless: z.string().optional(),
      neptune: z.string().optional(),
      neptunegraph: z.string().optional(),
      networkfirewall: z.string().optional(),
      networkflowmonitor: z.string().optional(),
      networkmanager: z.string().optional(),
      networkmonitor: z.string().optional(),
      notifications: z.string().optional(),
      notificationscontacts: z.string().optional(),
      oam: z.string().optional(),
      observabilityadmin: z.string().optional(),
      odb: z.string().optional(),
      opensearch: z.string().optional(),
      opensearchingestion: z.string().optional(),
      opensearchserverless: z.string().optional(),
      opensearchservice: z.string().optional(),
      organizations: z.string().optional(),
      osis: z.string().optional(),
      outposts: z.string().optional(),
      paymentcryptography: z.string().optional(),
      pcaconnectorad: z.string().optional(),
      pcs: z.string().optional(),
      pinpoint: z.string().optional(),
      pinpointsmsvoicev2: z.string().optional(),
      pipes: z.string().optional(),
      polly: z.string().optional(),
      pricing: z.string().optional(),
      prometheus: z.string().optional(),
      prometheusservice: z.string().optional(),
      qbusiness: z.string().optional(),
      qldb: z.string().optional(),
      quicksight: z.string().optional(),
      ram: z.string().optional(),
      rbin: z.string().optional(),
      rds: z.string().optional(),
      rdsdata: z.string().optional(),
      rdsdataservice: z.string().optional(),
      recyclebin: z.string().optional(),
      redshift: z.string().optional(),
      redshiftdata: z.string().optional(),
      redshiftdataapiservice: z.string().optional(),
      redshiftserverless: z.string().optional(),
      rekognition: z.string().optional(),
      resiliencehub: z.string().optional(),
      resourceexplorer2: z.string().optional(),
      resourcegroups: z.string().optional(),
      resourcegroupstagging: z.string().optional(),
      resourcegroupstaggingapi: z.string().optional(),
      rolesanywhere: z.string().optional(),
      route53: z.string().optional(),
      route53domains: z.string().optional(),
      route53profiles: z.string().optional(),
      route53recoverycontrolconfig: z.string().optional(),
      route53recoveryreadiness: z.string().optional(),
      route53resolver: z.string().optional(),
      rum: z.string().optional(),
      s3: z.string().optional(),
      s3api: z.string().optional(),
      s3control: z.string().optional(),
      s3outposts: z.string().optional(),
      s3tables: z.string().optional(),
      s3vectors: z.string().optional(),
      sagemaker: z.string().optional(),
      scheduler: z.string().optional(),
      schemas: z.string().optional(),
      secretsmanager: z.string().optional(),
      securityhub: z.string().optional(),
      securitylake: z.string().optional(),
      serverlessapplicationrepository: z.string().optional(),
      serverlessapprepo: z.string().optional(),
      serverlessrepo: z.string().optional(),
      servicecatalog: z.string().optional(),
      servicecatalogappregistry: z.string().optional(),
      servicediscovery: z.string().optional(),
      servicequotas: z.string().optional(),
      ses: z.string().optional(),
      sesv2: z.string().optional(),
      sfn: z.string().optional(),
      shield: z.string().optional(),
      signer: z.string().optional(),
      sns: z.string().optional(),
      sqs: z.string().optional(),
      ssm: z.string().optional(),
      ssmcontacts: z.string().optional(),
      ssmincidents: z.string().optional(),
      ssmquicksetup: z.string().optional(),
      ssmsap: z.string().optional(),
      sso: z.string().optional(),
      ssoadmin: z.string().optional(),
      stepfunctions: z.string().optional(),
      storagegateway: z.string().optional(),
      sts: z.string().optional(),
      swf: z.string().optional(),
      synthetics: z.string().optional(),
      taxsettings: z.string().optional(),
      timestreaminfluxdb: z.string().optional(),
      timestreamquery: z.string().optional(),
      timestreamwrite: z.string().optional(),
      transcribe: z.string().optional(),
      transcribeservice: z.string().optional(),
      transfer: z.string().optional(),
      verifiedpermissions: z.string().optional(),
      vpclattice: z.string().optional(),
      waf: z.string().optional(),
      wafregional: z.string().optional(),
      wafv2: z.string().optional(),
      wellarchitected: z.string().optional(),
      workmail: z.string().optional(),
      workspaces: z.string().optional(),
      workspacesweb: z.string().optional(),
      xray: z.string().optional(),
    }).array().optional(),
  ),
  ignore_tags: resolvableValue(
    z.object({
      key_prefixes: z.string().array().optional(),
      keys: z.string().array().optional(),
    }).array().optional(),
  ),
})

export type InputProps =
  & z.input<typeof InputSchema>
  & NodeProps

export function AwsProvider(props: Partial<InputProps>) {
  const { stack, awsProvider } = getRenderOptions()
  const default_tags = () =>
    props.default_tags || {
      tags: {
        'iac:stack-title': stack.title,
        'iac:stack-name': stack.name,
      },
    }
  const _title = (node: any) => props._title || node._props.region || `Cloud`
  return (
    <Shape
      _category={['provider', 'terraform']}
      _terraform={{
        required_providers: {
          aws: {
            source: 'aws',
            version: '6.28.0',
          },
        },
      }}
      _inputSchema={InputSchema}
      _direction='vertical'
      {...(awsProvider || {})}
      {...props}
      _title={_title}
      providerId='aws'
      default_tags={default_tags}
      _style={extendStyle(props, AWS_CLOUD)}
    />
  )
}

export const useAwsProvider = () => useTypedNode<InputProps>(AwsProvider)
