# for .devcontainer.json use only
# Ignore everything
**

# Allow files and directories
!/package.json
!/docker/release/entrypoint.sh
!/*/*/package.json
!/*/*/tsconfig.json
!/*/*/src
!/*/*/bin
!/pnpm-lock.yaml
!/pnpm-workspace.yaml
