# for .devcontainer.json use only
# Ignore everything
**

# Allow files and directories
!/deno.*
!/.version
!/*/*/deno.jsonc
!/*/*/src/**
!/workspace/**


# Ignore support project files
build/**
standalone/**
scripts/**
