# https://hub.docker.com/r/denoland/deno/tags?name=debian
# https://docs.docker.com/reference/dockerfile/
FROM denoland/deno:debian-<%= VERSION_DENO %>

RUN echo 'Essential dependencies' \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    procps \
    git \
    curl \
    gpg \
    zip \
    unzip \
    vim \
    openssh-client \
    ca-certificates \
    lsb-release \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
