devcontainer:
  type: site
  volumns:
    - source: ../../images/40-site/fs-root/workspace/.vscode
      target: /workspace/.vscode
      skipCheck: true
  extensions:
    - anthropic.claude-code
docker:
  images:
    engine:
      volumns:
        - source: ../../../sites
    site:
      volumns:
        - source: ../../../sites/www/static
          target: /workspace/.dinghy/site/static
          skipCheck: true
        - source: ../../images/40-site/fs-root/workspace/.dinghy/site/docusaurus.config.ts
          target: /workspace/.dinghy/site/docusaurus.config.ts
          skipCheck: true
        - source: ../../images/40-site/fs-root/workspace/.dinghy/site/package.json
          target: /workspace/.dinghy/site/package.json
          skipCheck: true
        - source: ../../images/40-site/fs-root/workspace/.dinghy/site/tsconfig.json
          target: /workspace/.dinghy/site/tsconfig.json
          skipCheck: true
        - source: ../../images/40-site/fs-root/workspace/.dinghy/site/yarn.lock
          target: /workspace/.dinghy/site/yarn.lock
          skipCheck: true
        - source: ../../../sites/www/src
          target: /workspace/.dinghy/site/src
          skipCheck: true
        - source: ../../../sites/www/slides
          target: /workspace/.dinghy/site/slides
          skipCheck: true
