ARG BUILD_ARCH=arm64
FROM <%= DOCKER_IMAGE_BASE_TAG %>-linux-$BUILD_ARCH

RUN echo 'Install docker' \
   && install -m 0755 -d /etc/apt/keyrings \
   && curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc\
   && chmod a+r /etc/apt/keyrings/docker.asc \
   && echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null \
   && apt-get update \
   && apt-get -y install docker-ce-cli\
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/*

COPY docker/images/61-release-base/fs-root /