/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    "references": [
        {
            type: "category",
            label: "/References",
            collapsible: false,
            link: {
                type: "doc",
                id: "rewrite-url",
            },
            items: [
                {
                    type: "doc",
                    label: "/References/Commands",
                    id: "rewrite-url",
                },
                {
                    type: "doc",
                    label: "/References/Attributes",
                    id: "rewrite-url",
                },
                {
                    type: "doc",
                    label: "/References/Diagrams",
                    id: "rewrite-url",
                },
                {
                    type: "category",
                    label: "/References/TF AWS",
                    collapsible: false,
                    link: {
                        type: "doc",
                        id: "rewrite-url",
                    },
                    items: [
                        {
                            type: "doc",
                            label: "/References/TF AWS/Foundation",
                            id: "rewrite-url",
                        },
                        {
                            type: "category",
                            label: "Services",
                            link: {
                                type: "doc",
                                id: "README",
                            },
                            items: [{
                                type: "autogenerated",
                                dirName: "services",
                            }],
                        }
                    ],
                },
            ],
        },
    ],
};
