FROM <%= DOCKER_IMAGE_RELEASE_BASE_TAG %>

COPY . /reactiac

RUN cd /reactiac && \
    . /root/.bashrc && \
    deno run -A cache-installer.ts && \
    rm -rf deno.* cache-installer.ts engine/packages-to-cache.ts engine/deno.jsonc