ARG BUILD_ARCH=arm64
FROM <%= DOCKER_IMAGE_BASE_TAG %>-linux-$BUILD_ARCH

RUN echo 'Install opentofu' \
    && curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh \
    && chmod +x install-opentofu.sh \
    && ./install-opentofu.sh --install-method standalone --opentofu-version <%= VERSION_OPENTOFU %> \
    && rm -rf install-opentofu.sh \
    && ln -s /usr/local/bin/tofu /usr/bin/tf

COPY docker/images/50-tf/fs-root /    
RUN echo 'Install aws provider' \
     && cd /terraform \
     && tf init
