FROM <%= DOCKER_IMAGE_BASE_TAG %>

# # https://developer.hashicorp.com/terraform/install
RUN echo 'Install terraform' \
   && curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list \
    && apt-get update \
    # && apt list -a terraform \
    && apt-get -y install terraform=<%= VERSION_TERRAFORM %> \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

RUN echo 'Install terraform aws provider' \
   && mkdir -p /terraform \
    && cd /terraform \
    && printf "terraform {\nrequired_providers {\nmycloud = {\nsource  = \"aws\"\nversion = \"<%= VERSION_AWSPROVIDER %>\"\n}\n}\n}" > provider.tf \
    && terraform init


RUN echo 'Install aws cli' \
   && apt-get update \
    # && apt list -a awscli \
    && apt-get -y install awscli=<%= VERSION_AWSCLI %> \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

COPY docker/images/50-tf/fs-root /    