# https://github.com/dinghydev/dinghy/blob/main/core/tf-aws/src/composites/iam/types.ts#RolePolicySchema
id-override-demo-policy:
  - id: override-by-id
    permission: readonly
    buckets:
      - dinghy-demo-site-overridable
eu-west-2-activated-services-all-access:
  - actions:
      - ec2:*
      - ecs:*
    resources:
      - arn:aws:ec2:eu-west-2:*:*
      - arn:aws:ecs:eu-west-2:*:*
