ARG BUILD_ARCH=arm64
FROM <%= DOCKER_IMAGE_YARN_BASE_TAG %>-linux-$BUILD_ARCH

COPY docker/images/40-site/fs-root /

RUN echo 'Install docusaurus dependencies' \
   && cd /workspace/.dinghy/site \
    && yarn install --immutable