name: release-docker

on:
  # push:
    # branches: [main]
  workflow_dispatch:
  # workflow_run:
  #     workflows: ['verification']
  #     types: [completed]
  #     branches: [main]

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout
        
jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: commit-rev-count
        run: |
          gh api graphql -f query='query CommitRevCount{
              repository(owner:"${{ github.repository_owner }}",name:"${{ github.event.repository.name }}") {
                name
                object(oid: "${{ github.sha }}"){
                  ... on Commit {
                    message
                    id
                    history(first: 0) {
                      totalCount
                    }
                  }
                }
              }
            }' > commit_rev_count_data.json
          COMMIT_REV_COUNT="$(jq -r '.data.repository.object.history.totalCount' commit_rev_count_data.json)"
          echo "COMMIT_REV_COUNT=$COMMIT_REV_COUNT" >> $GITHUB_ENV
          echo "COMMIT_REV_COUNT=$COMMIT_REV_COUNT"
          rm commit_rev_count_data.json
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22.14.0
      - name: Configure AWS Credentials for public ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::313225491971:role/${{ secrets.AWS_DEPLOY_ROLE }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: publish docker image
        run: |
          # aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 313225491971.dkr.ecr.eu-west-1.amazonaws.com
          # aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/f2v6q7q7
          pnpm release-version-update
          pnpm aws-login
          pnpm docker-publish-linux-amd64
          pnpm docker-publish-linux-arm64
          # pnpm release-version-reset
        env:
          DOCKER_PUSH: ${{ env.COMMIT_REV_COUNT }}

