name: release-runner

on:
  # push:
    # branches: [main]
  workflow_dispatch:
  # workflow_run:
  #     workflows: ['verification']
  #     types: [completed]
  #     branches: [main]

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout
        
jobs:
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cached packages
        id: restore-js-packages
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/deno
            ~/.local/share/pnpm
          key: ${{ runner.os }}-js-packages-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/deno.lock') }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.4
      - name: commit-rev-count
        run: |
          gh api graphql -f query='query CommitRevCount{
              repository(owner:"${{ github.repository_owner }}",name:"${{ github.event.repository.name }}") {
                name
                object(oid: "${{ github.sha }}"){
                  ... on Commit {
                    message
                    id
                    history(first: 0) {
                      totalCount
                    }
                  }
                }
              }
            }' > commit_rev_count_data.json
          COMMIT_REV_COUNT="$(jq -r '.data.repository.object.history.totalCount' commit_rev_count_data.json)"
          echo "COMMIT_REV_COUNT=$COMMIT_REV_COUNT" >> $GITHUB_ENV
          echo "COMMIT_REV_COUNT=$COMMIT_REV_COUNT"
          rm commit_rev_count_data.json
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
          role-to-assume: arn:aws:iam::313225491971:role/${{ secrets.AWS_DEPLOY_ROLE }}
      - name: publish runner
        run: |
          (cd clients/runner ; deno task release-version update)
          (cd clients/runner ; deno task publish)
          # (cd clients/runner; deno task release-version reset)
        env:
          COMMIT_REV_COUNT: ${{ env.COMMIT_REV_COUNT }}
          

          