name: verification
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:


jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.3.3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
      - run: pnpm show-info
      - name: verification
        run: |
          pnpm clean
          pnpm install --frozen-lockfile
          pnpm -r build
          pnpm -r test
